<div style="margin: 10px;">

<h4>OChatD only has one simple rule:<h4>

<h5 style="margin-left: 15px;">1. Be nice.</h5>

<strong>However, we do have a list of guidelines and etiquette suggestions:</strong>

    <ul>
        <li>New users are free to lurk as long as you wish before introducing yourself. Say hello and introduce yourself any time you feel comfortable.</li>
        <li>Please help maintain a positive, supportive, and welcoming atmosphere.</li>
        <li>Warmly welcome anyone joining the chat, especially new users (new user's names will display in green)</li>
        <li>There's no need to ask permission to ask questions, feel free to just ask! :)</li>
        <li>Use tact, but don't be afraid or hold back describing your obsessions or compulsions for fear of "triggering" others in the chat. On that note, you acknowledge you may find some discussion in the chat disturbing or triggering. Avoiding triggers is unhelpful for OCD and self-censorship hinders support discussions.</li>
        <li>We have no explicit rules against profanity, as long as it's not directed towards anyone or violating rule #1.</li>
        <li>We strongly discourage disclosing your real life identity in the chat, including things like addresses, phone numbers, last names, etc. This will help you feel more comfortable sharing.</li>
    </ul>

    <h4>Tips and tricks:</h4>

    <ul>
        <li>The chat consists of two main rooms: Support and General. Support is for OCD specific talk and mental health support, and General is for everything else. Sometimes the two cross over, and it's no big deal, but we ask that you keep Support on topic so that people who need help can ask for and receive it.</li>
        <li>If you're having an issue with someone in the chat, or have a suggestion for how to make the chat better please feel free to message the mods from the sidebar. It will go directly to the group of mods, who will respond to you via PM.</li>
        <li>To private message another user, click on their username from the chat room or go to https://chat.ocd.community/p/theirusername. Apple users may not get notifications for PMs, so please keep that in mind.</li>
    </ul>
</div>
