<style>
h1.site-headline {
    text-rendering: optimizeLegibility;
}
</style>
<h1 class="site-headline mdl-typography--headline mdl-typography--text-center">
    Welcome to OChatD, the best community and support chat for those affected by OCD on the entire internet.
</h1>

<h3 class="site-headline mdl-typography--headline mdl-typography--text-center">New users, <a href="/register">register here</a>.</h2>
<h3 class="site-headline mdl-typography--headline mdl-typography--text-center">Existing users, <a href="/login">login here</a>.</h2>
