<script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-load-image/2.10.0/load-image.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/javascript-canvas-to-blob/3.6.0/js/canvas-to-blob.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/autosize.js/3.0.20/autosize.min.js"></script>

<style>
form#compose {
    position: fixed;
    bottom: 0px;
    width: 100%;
    border-top: 1px solid #DDD;
}

textarea#compose-message {
    box-sizing: border-box;
    width: 100%;
    min-height: 40px;
    max-height: 180px;
    resize: none;
    padding: 5px;
    padding-right: 70px;
    padding-left: 35px;

    border: none;
    outline: none;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
}

button#send-button {
    position: fixed;
    cursor: pointer;
    right: 0px;
    bottom: 0px;
    background: none;
    border: none;
    border-left: 1px solid #DDD;
    width: 70px;
    height: 50px;
    outline: none;
}

label#attach-media-button {
    display: block;
    position: fixed;
    cursor: pointer;
    left: 0px;
    bottom: 0px;
    background: none;
    border: none;
    border-right: 1px solid #DDD;
    width: 30px;
    height: 50px;
    line-height: 50px;
    text-align: center;
}

span.rounded > img.avatar {
    display: inline;
    height: 100%;
    width: auto;
    min-width: 100%;
    margin: 0 auto;
}

section#content {
    overflow-y: scroll;
    margin-bottom: 50px;
}
span.timestamp {
    color: #DDD;
    float: right;
}

span.rounded {
    vertical-align: middle;
    display: inline-block;
    position: relative;
    border-radius: 50%;
    width: 40px;
    height: 40px;
    margin: 0 auto;
    overflow: hidden;
}
div#chat-log img {
    max-width: 95%;
}
span.sender {
    margin-left: 10px;
    font-weight: bold;
    position: relative;
    top: 2px;
}

span.sender.source-gliph:after {
    content: ' (via gliph)';
    color: #DDD;
    font-weight: normal;
}

div.message {
    margin-left: 50px;
}

blockquote {
  background: #f9f9f9;
  border-left: 10px solid #ccc;
  margin: 1.5em 10px;
  padding: 0.5em 10px;
  quotes: "\201C""\201D""\2018""\2019";
}
blockquote:before {
  color: #ccc;
  content: open-quote;
  font-size: 4em;
  line-height: 0.1em;
  margin-right: 0.25em;
  vertical-align: -0.4em;
}
blockquote p {
  display: inline;
}

input[type="file"] {
    display: none;
}

div#pending-media {
    position: relative;
    top: -1px;
    border-bottom: 1px solid #CCC;
}

div#pending-media canvas, div#pending-media img {
    padding: 2px;
    max-height: 125px;
}
</style>


<div id="chat-log">

</div>

<form id="compose">

    <div id="pending-media"></div>

    <input type="file" id="files" accept="image/*">
    <label for="files" class="stretch-height" id="attach-media-button"><i class="fa fa-plus" aria-hidden="true"></i></label>

    <textarea id="compose-message" placeholder="Don't be shy, type a message!" autocomplete="off"></textarea>

    <button class="stretch-height" id="send-button">Send &raquo;</button>

</form>

<script>
var ROOM_ID = 'dd0c62bd-c4f2-4286-affa-256bfcc93955';

<? if ($this->routeParam('community') == 'ocdmods'): ?>
var ROOM_ID = 'e6ddc009-a7c0-4bf9-8637-8a3da4d65825';
<? endif; ?>

var autolinker = new Autolinker( {
    urls : {
        schemeMatches : true,
        wwwMatches    : true,
        tldMatches    : true
    },
    email       : false,
    phone       : false,
    mention     : false,
    hashtag     : false,

    stripPrefix : false,
    newWindow   : true,

    truncate : {
        length   : 0,
        location : 'end'
    },

    className : ''
} );


var latestMessageTimestamp = 0;
var receivedMessageKeys = {};

function getLatestMessages(id) {
    $.getJSON('/messages/' + id, function(messages) {
        for (i=0; i<messages.length; i++) {
            message = messages[i];
            if (receivedMessageKeys[message.key]
             || message.timestamp < latestMessageTimestamp
             || message.senderName == 'ocdbot'
            ) {
                continue;
            }
            latestMessageTimestamp = message.timestamp;
            receivedMessageKeys[message.key] = true;

            mTimestamp = moment.unix(message.timestamp);
            timeDisplay = mTimestamp.fromNow();
            timeDisplayAlt = mTimestamp.format('YYYY-MM-DD HH:mm:ss');

            messageRendered = autolinker.link(markdown.toHTML(message.message));

            $('#chat-log').append(
                '<span class="rounded"><img class="avatar" src="' + message.senderAvatar + '"></span>' +
                '<span class="timestamp" data-timestamp="'+message.timestamp+'" title="'+timeDisplayAlt+'">' + timeDisplay + '</span>' +
                '<span class="sender source-'+ message.source +'">' + message.senderName + ':</span> ' +
               '<div class="message">'+ messageRendered + '</div>'
            );
            if (message.media) {
                for (j=0; j<message.media.length; j++) {
                    $('#chat-log').append('<div class="message"><img src="' + message.media[j].thumbnail + '"></div>');
                }
            }

        }
        setTimeout(function(){ updateScroll('content'); }, 100);
    });
};

setInterval(function(){
    $('span.timestamp').each(function() {
        mTimestamp = moment.unix($(this).data('timestamp'));
        $(this).text(mTimestamp.fromNow());
    });
}, 60000);

function updateScroll(el) {
    var element = document.getElementById(el);
    element.scrollTop = element.scrollHeight;
}
updateScroll('content');

EventBus.addEventListener('window:resize:height', function() {
    updateScroll('content');
});

$(document).ready(function() {

    $('#compose-message').each(function(){
        autosize(this);
    }).on('autosize:resized', function(){
        newHeight = $(this).height() + 12;
        $('section#content').css('margin-bottom', newHeight + 'px');
        $('.stretch-height').height(newHeight);
        $('.stretch-height').css('line-height', newHeight + 'px');
        updateScroll('content');
    });

    getLatestMessages(ROOM_ID);

    $('form#compose').submit(function(event) {
     event.preventDefault();
     if (!$('#compose-message').val().trim()) {
         return;
     }

     $('#compose-message').attr('disabled','disabled');
     $('button#send-button').html('Sending');
     $.post('/messages/' + ROOM_ID, { message: $('#compose-message').val() }, function(result) {
         $('#compose-message').removeAttr('disabled');
         $('#compose-message').val('');
         $('button#send-button').html('Send &raquo;');
         autosize.update($('#compose-message'));
         $('#compose-message').focus();
     });
    });

});


var shiftDown = false;
var chatForm = $("#compose");
var messageBox = chatForm.children("textarea");

$(document).keypress(function (e) {
    if(e.keyCode == 13) {
        if(messageBox.is(":focus") && !shiftDown) {
            e.preventDefault(); // prevent another \n from being entered
            chatForm.submit();
        }
    }
});

$(document).keydown(function (e) {
    if(e.keyCode == 16) shiftDown = true;
});

$(document).keyup(function (e) {
    if(e.keyCode == 16) shiftDown = false;
});




function handleFileSelect(evt) {
    var file = evt.target.files[0];
    console.log(file);

    if (file.type == 'image/gif') {
        var reader = new FileReader();
         reader.onload = function (e) {
            $('div#pending-media').append('<img src="'+e.target.result+'">');
            newHeight = $('form#compose').height() + 1;
            $('section#content').css('margin-bottom', newHeight + 'px');
            updateScroll('content');
         }
         reader.readAsDataURL(file);
    } else {
        loadImage(
            file,
            function (img) {
                $('div#pending-media').append(img);
                newHeight = $('form#compose').height() + 1;
                $('section#content').css('margin-bottom', newHeight + 'px');
                updateScroll('content');
            },
            {
                maxWidth: 700,
                maxHeight: 500,
                canvas: true
            }
        );
    }
}

document.getElementById('files').addEventListener('change', handleFileSelect, false);

</script>
