<script src="https://cdnjs.cloudflare.com/ajax/libs/markdown.js/0.5.0/markdown.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/autolinker/1.4.0/Autolinker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-load-image/2.10.0/load-image.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/javascript-canvas-to-blob/3.6.0/js/canvas-to-blob.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/autosize.js/3.0.20/autosize.min.js"></script>


<style>
span.rounded > img.avatar {
    display: inline;
    height: 100%;
    width: auto;
    min-width: 100%;
    margin: 0 auto;
}

span.timestamp {
    color: #BBB;
    float: right;
}

span.rounded {
    vertical-align: middle;
    display: inline-block;
    position: relative;
    border-radius: 50%;
    width: 40px;
    height: 40px;
    margin: 0 auto;
    overflow: hidden;
}
div#chat-log img {
    max-width: 95%;
}
span.sender {
    margin-left: 10px;
    font-weight: bold;
    position: relative;
    top: 2px;
}

span.sender.source-gliph:after {
    content: ' (via gliph)';
    color: #BBB;
    font-weight: normal;
}

div.message a {
    word-break: break-all;
}

div.message {
    margin-left: 50px;
}

blockquote {
  background: #f9f9f9;
  border-left: 10px solid #ccc;
  margin: 1.5em 10px;
  padding: 0.5em 10px;
  quotes: "\201C""\201D""\2018""\2019";
}
blockquote:before {
  color: #ccc;
  content: open-quote;
  font-size: 4em;
  line-height: 0.1em;
  margin-right: 0.25em;
  vertical-align: -0.4em;
}
blockquote p {
  display: inline;
}

input[type="file"] {
    display: none;
}

div#pending-media {
    background-color: #FFF;
}

div#pending-media canvas, div#pending-media img {
    margin: 5px;
    max-height: 75px;
}

form#compose {
    width: 100%;
}

form#compose button {
}

textarea#compose-message, textarea#compose-message:focus {
    box-sizing: border-box;
    min-height: 20px;
    max-height: 180px;
    width: 100%;
    resize: none;
    font-size: 16px;
    padding: 5px 60px;
    padding-top: 15px;
    border: none;
    outline: none;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
}

button#send-button {
    position: fixed;
    cursor: pointer;
    right: 0px;
    bottom: 0px;
    background: none;
    border: none;
    border-left: 1px solid #DDD;
    width: 70px;
    height: 50px;
    outline: none;
}

label#attach-media-button {
  height: 100%;
  width: 100%;
  cursor: pointer;
  position: absolute;
  top: 0px;
  right: 0px;
  z-index: 2;
}

.footer-light {
    background-color: #FFF;
    padding: 0px;
}

main#content {
    padding: 20px;
}

form#compose .mdl-grid {
    padding: 0;
}
form#compose .mdl-button {
    min-width: 20px !important;
    position: fixed;
    bottom: 10px;
    height: 40px;
}
form#compose .mdl-button.send {
    right: 0px;
}
</style>

  <main id="content" class="mdl-layout__content" style="flex: 1 1 auto; overflow-y: scroll;">
    <div id="chat-log"></div>
  </main>

  <footer class="mdl-mega-footer footer-light mdl-shadow--8dp">
    <form id="compose">
    <div id="pending-media"></div>

    <div class="mdl-grid">

        <div class="attach mdl-button mdl-js-button mdl-js-ripple-effect">
          <label id="attach-media-button" for="files"></label>
          <input type="file" id="files" accept="image/*">
          <i class="material-icons">attach_file</i>
        </div>

        <textarea id="compose-message" placeholder="Message" autocomplete="off"></textarea>

        <button class="send mdl-button mdl-js-button mdl-js-ripple-effect">
          <i class="material-icons">send</i>
        </button>
    </div>


    </form>

  </footer>

<script>

var ROOM_ID = 'dd0c62bd-c4f2-4286-affa-256bfcc93955';

<? if ($this->routeParam('community') == 'ocdmods'): ?>
var ROOM_ID = 'e6ddc009-a7c0-4bf9-8637-8a3da4d65825';
<? endif; ?>

<? if ($this->routeParam('community') == 'test'): ?>
var ROOM_ID = 'f68c5b32-ab99-4955-acc8-3f9f887dcf22';
<? endif; ?>

</script>

<? if ($_SERVER['HTTP_HOST'] === 'ocdchat.dev'): ?>
    <script src="/socket.io.min.js"></script>
    <script>
        var socket = io('localhost:9999');
    </script>
<? else: ?>
    <script src="/socket.io/socket.io.js"></script>
    <script>
        var socket = io();
    </script>
<? endif;?>

<script>
    socket.on('connect', function(){
        socket.emit('join-room', ROOM_ID);
        $('svg.logo, img.logo')
            .removeClass('disconnected')
            .addClass('connected');
    });

    socket.on('disconnect', function(){
        $('svg.logo')
            .removeClass('connected')
            .addClass('disconnected');
    });

    socket.on('new-message', function (data) {
        getLatestMessages(ROOM_ID);
    });

    socket.on('media-upload-progress', function (data) {
        displayMediaProgress(data.mediaId, data.percent);
    });

    socket.on('media-upload-complete', function (mediaId) {
        displayMedia(mediaId);
    });
</script>


<script>
var autolinker = new Autolinker( {
    urls : {
        schemeMatches : true,
        wwwMatches    : true,
        tldMatches    : true
    },
    email       : false,
    phone       : false,
    mention     : false,
    hashtag     : false,

    stripPrefix : false,
    newWindow   : true,

    truncate : {
        length   : 0,
        location : 'end'
    },

    className : ''
} );


var latestMessageTimestamp = 0;
var receivedMessageKeys = {};

function getLatestMessages(id) {
    var success = function(messages) {
        $('svg.logo, img.logo')
            .removeClass('disconnected')
            .addClass('connected');
        for (i=0; i<messages.length; i++) {
            var message = messages[i];
            if (!message
             || receivedMessageKeys[message.key]
             || message.timestamp < latestMessageTimestamp
             || message.senderName == 'ocdbot'
            ) {
                continue;
            }
            latestMessageTimestamp = message.timestamp;
            receivedMessageKeys[message.key] = true;

            var mTimestamp     = moment.unix(message.timestamp);
            var timeDisplay    = mTimestamp.fromNow();
            var timeDisplayAlt = mTimestamp.format('YYYY-MM-DD HH:mm:ss');

            var messageRendered = autolinker.link(markdown.toHTML(message.message));

            $('#chat-log').append(
                '<span class="rounded"><img class="avatar" src="' + message.senderAvatar + '"></span>' +
                '<span class="timestamp" data-timestamp="'+message.timestamp+'" title="'+timeDisplayAlt+'">' + timeDisplay + '</span>' +
                '<span class="sender source-'+ message.source +'">' + message.senderName + ':</span> ' +
               '<div class="message">'+ messageRendered + '</div>'
            );
            if (message.media && message.source =='gliph') {
                for (j=0; j<message.media.length; j++) {
                    $('#chat-log').append('<div class="message"><img src="' + message.media[j].thumbnail + '"></div>');
                }
            }
            if (message.media && message.source =='native') {
                for (j=0; j<message.media.length; j++) {
                    var parts = message.media[j].split('.');
                    var $div = $('<div class="message media"><span class="loaded"></span></div>');
                    var $img = $('<img alt="Loading..." class="chat-media '+parts[1]+'" id="'+parts[0]+'" data-src="/uploads/default/' + message.media[j] + '">');
                    $img.attr('src', $img.data('src'));
                    var tmpImg = new Image();
                    tmpImg.onload = function() { console.log('image loaded'); updateScroll('content'); };
                    tmpImg.src = $img.attr('src');
                    $('#chat-log').append($div.append($img));
                }
            }

        }
        setTimeout(function(){ updateScroll('content'); }, 100);
    }; // end success function

    $.ajax({
      dataType: 'json',
      tryCount : 0,
      retryLimit : 50000,
      url: '/messages/' + id,
      success: success,
      error : function(xhr, textStatus, errorThrown ) {
          $('svg.logo')
              .removeClass('connected')
              .addClass('disconnected');
          this.tryCount++;
          if (this.tryCount <= this.retryLimit) {
              console.log('Error getting messages. Retrying...');
              $.ajax(this);
              return;
          }
          return;
      }
    });
    $.getJSON('/messages/' + id, );
};

function displayMediaProgress(mediaId, percent) {
    percentRounded = Math.round(percent);
    $('img#'+mediaId).parent().find('span.loaded').text(percentRounded + '%');
};

function displayMedia(mediaId) {
    //var mediaId = e.target;
    var $img    = $('img#'+mediaId);
    $img.removeAttr('src').attr('src', $img.data('src'));
    $img.parent().find('span.loaded').remove();
};

function announceMediaProgress(e) {
    socket.emit('media-upload-progress', e.target);
};

function announceMediaReady(e) {
    socket.emit('media-upload-complete', e.target);
};

EventBus.addEventListener('chat:media-upload-complete', announceMediaReady);
EventBus.addEventListener('chat:media-upload-progress', announceMediaProgress);

//EventBus.addEventListener('chat:media-upload-complete', displayMedia);


setInterval(function(){
    $('span.timestamp').each(function() {
        mTimestamp = moment.unix($(this).data('timestamp'));
        $(this).text(mTimestamp.fromNow());
    });
}, 60000);

function updateScroll(el) {
    var element = document.getElementById(el);
    element.scrollTop = element.scrollHeight;
}
updateScroll('content');

EventBus.addEventListener('window:resize', function() {
    updateScroll('content');
});

function sendMessage(mediaFiles) {
     $.post('/messages/' + ROOM_ID, { message: $('#compose-message').val(), media: mediaFiles }, function(result) {
         $('#compose-message').removeAttr('disabled');
         $('#compose-message').val('');
         $('button#send-button').removeAttr('disabled');
         $('button#send-button').html('Send &raquo;');
         $('#pending-media').html('');
         autosize.update($('#compose-message'));
         $('#compose-message').focus();
     });
}

$(document).on('wake', function() {
    console.log('Waking up...');
    getLatestMessages(ROOM_ID);
});

$(document).ready(function() {
    $('#compose-message').focus();

    $('#compose-message').each(function() {
        autosize(this);
    }).on('autosize:resized', function() {
        newHeight = $('form#compose').height() + 1;
        $('.stretch-height').css('height', newHeight + 'px');
        $('.stretch-height').css('line-height', newHeight + 'px');
        updateScroll('content');
    });

    getLatestMessages(ROOM_ID);

    $('form#compose').submit(function(event) {

        event.preventDefault();

        if (mediaBlobs.length == 0 && !$('#compose-message').val().trim()) {
            return;
        }

        $('#compose-message').attr('disabled','disabled');
        $('#send-button').attr('disabled','disabled');

        if (mediaBlobs.length > 0) {

            var mediaManager = new MediaManager();
            mediaManager.addBlobs(mediaBlobs, function(media) {
                sendMessage(this.getMediaFilenames());
                mediaBlobs = [];
                this.upload();
            });

            return;
        }

        if (!$('#compose-message').val().trim()) {
            return;
        }

        sendMessage(false);

    });

});


var shiftDown = false;
var chatForm = $("#compose");
var messageBox = $('#compose-message');

$(document).keypress(function (e) {
    if(e.keyCode == 13) {
        if(messageBox.is(":focus") && !shiftDown) {
            e.preventDefault(); // prevent another \n from being entered
            chatForm.submit();
        }
    }
});

$(document).keydown(function (e) {
    if(e.keyCode == 16) shiftDown = true;
});

$(document).keyup(function (e) {
    if(e.keyCode == 16) shiftDown = false;
});


var mediaBlobs = [];

function handleFileSelect(evt) {
    var file = evt.target.files[0];
    console.log(file);

    if (file.type == 'image/gif') {

        mediaBlobs.push(file);
        console.log(mediaBlobs);

        var reader = new FileReader();
         reader.onload = function (e) {
             $('div#pending-media').append(
                 $('<img src="'+e.target.result+'">')
             );
             updateScroll('content');
         }
         reader.readAsDataURL(file);
    } else {
        loadImage(
            file,
            function (img) {
                $('div#pending-media').append(img);
                updateScroll('content');
                img.toBlob(function (blob) {
                        mediaBlobs.push(blob);
                        console.log(mediaBlobs);
                }, 'image/jpeg');
            },
            {
                maxWidth: 700,
                maxHeight: 500,
                canvas: true
            }
        );
    }

    $('#compose-message').focus();
}

document.getElementById('files').addEventListener('change', handleFileSelect, false);

</script>
