<form method="post" action="<?= $this->url('auth-change-password') ?>" class="auth">

    <label for="password">Current Password:</label>
    <input type="password" name="password" id="current-password" placeholder="Current Password"><br>

    <label for="new-password">New Password:</label>
    <input type="password" name="newPassword" id="new-password" placeholder="New Password"><br>
    <input type="checkbox" id="show-pass"><br>

    <input type="hidden" name="__csrf_value" value="<?= $this->csrfToken() ?>">

    <input type="submit" value="Change Password">
</form>

<script>
$.toggleShowPassword({
    field: '#new-password',
    control: '#show-pass'
});
</script>
