<!DOCTYPE html>
<html lang="en">
<head>
    <script>var APP_VERSION = '<?= Common\Helper\Git::version()['short'] ?>';</script>
    <?= $this->headTitle('OChatD')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#FFFFF">
    <link rel="stylesheet" href="/material-icons/material-icons.css">
    <link rel="stylesheet" href="/mdl/material.indigo-pink.min.css">
    <link rel="stylesheet" href="/roboto/roboto.css">
    <link rel="stylesheet" href="/material.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script defer src="/mdl/material.min.js"></script>
    <script src="/eventbus.min.js"></script>
    <script src="/global.js"></script>
    <script src="/media-manager.js"></script>
</head>
<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="chat-header mdl-layout__header">
    <div class="mdl-layout-icon">
        <img class="logo inline-svg" src="/chat.svg">
    </div>
    <div class="mdl-layout__header-row">
      <span class="mdl-layout__title"></span>
      <div class="mdl-layout-spacer"></div>
      <nav class="mdl-navigation">

        <? if ($this->ident()): ?>

            <button id="menu-upper-right"
                    class="mdl-button mdl-js-button mdl-button--icon">
              <i class="material-icons">more_vert</i>
            </button>

            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                for="menu-upper-right">

                <a class="mdl-menu__item" href="<?= $this->url('community-chat', ['community' => 'ocd']) ?>">Chat</a>
                <a class="mdl-menu__item" href="<?= $this->url('avatar-form') ?>">Change Avatar</a>
                <a class="mdl-menu__item mdl-menu__item--full-bleed-divider" href="<?= $this->url('auth-logout') ?>">Logout</a>

                <div disabled class="mdl-menu__item" id="app-version">...</div>
                <script>document.getElementById('app-version').innerText = APP_VERSION;</script>

            </ul>

        <? else: ?>

            <a class="mdl-navigation__link" href="<?= $this->url('auth-login-form') ?>">Login</a>
            <a class="mdl-navigation__link" href="<?= $this->url('auth-register-form') ?>">Register</a>

        <? endif ?>

      </nav>
    </div>
  </header>


  <?= $this->content ?>
</div>

</body>
</html>
