<!DOCTYPE html>
<html lang="en">
<head>
    <?= $this->headTitle('OChatD')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#FFFFF">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link rel="stylesheet" href="/material.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <script src="/eventbus.min.js"></script>



    <script src="/global.js"></script>
    <script src="/media-manager.js"></script>
</head>
<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout-icon">
        <img class="logo inline-svg" src="/chat.svg">
    </div>
    <div class="mdl-layout__header-row">
      <span class="mdl-layout__title"></span>
      <div class="mdl-layout-spacer"></div>
      <nav class="mdl-navigation">
            <? if ($this->ident()): ?>
        <a class="mdl-navigation__link" href="<?= $this->url('community-chat', ['community' => 'ocd']) ?>">Chat</a>
        <a class="mdl-navigation__link" href="<?= $this->url('avatar-form') ?>">Change Avatar</a>
        <a class="mdl-navigation__link" href="<?= $this->url('auth-logout') ?>">Logout</a>
            <? else: ?>
        <a class="mdl-navigation__link" href="<?= $this->url('auth-login-form') ?>">Login</a>
        <a class="mdl-navigation__link" href="<?= $this->url('auth-register-form') ?>">Register</a>
            <? endif ?>
      </nav>
    </div>
  </header>

  <?= $this->content ?>
</div>

</body>
</html>

